<?php
return array(
    'Getting Started' => array(
        'getting-started' => 'Introduction',
        'install-fluent-forms' => 'Install Fluent Forms',
        'upgrade-to-pro-add-on' => 'Upgrade to Pro',
        'user-interface' => 'User Interface',
        'glossary' => 'Glossary',
    ),
    'Creating Forms' => array(
        '_flat' => array(
            'creating-forms-overview' => 'Overview',
        ),
        'Form Builder Basics' => array(
            'create-a-form' => 'Create a Form',
            'using-and-customizing-pre-built-quick-forms' => 'Pre-built Quick Forms',
            'create-a-form-with-ai' => 'Create with Fluent Forms AI',
            'create-a-form-with-openai-chatgpt' => 'Create with OpenAI ChatGPT',
        ),
        'Conversational Forms' => array(
            'create-a-conversational-form' => 'Create a Conversational Form',
            'design-a-conversational-form' => 'Design a Conversational Form',
        ),
        'Specialized Form Types' => array(
            'create-a-post-form' => 'Post Form',
            'create-a-wordpress-user-registration-form' => 'User Registration Form',
            'create-a-wordpress-user-update-form' => 'User Update Form',
            'creating-a-multi-step-form' => 'Multi-Step Form',
            'surveys-and-polls' => 'Surveys & Polls',
            'creating-a-personality-quiz-form' => 'Personality Quiz Form',
            'inline-opt-in-form' => 'Inline Opt-in Form',
        ),
    ),
    'Form Fields' => array(
        '_flat' => array(
            'form-fields-overview' => 'Overview',
        ),
        'General Fields' => array(
            'adding-a-simple-text-input-field' => 'Simple Text',
            'adding-a-text-area-input-field' => 'Text Area',
            'name-input-field' => 'Name',
            'email-address-input-field' => 'Email Address',
            'numeric-input-field' => 'Numeric',
            'phonemobile-input-field' => 'Phone / Mobile',
            'address-input-field' => 'Address',
            'website-url-input-field-guide' => 'Website URL',
            'adding-a-mask-input-field-guide' => 'Mask Input',
            'dropdown-field' => 'Dropdown',
            'radio-field' => 'Radio',
            'checkbox-field' => 'Checkbox',
            'multiple-choice-field' => 'Multiple Choice',
            'country-list-field' => 'Country List',
            'time-date-input-field' => 'Time & Date',
            'file-upload-input-field' => 'File Upload',
            'image-upload-input-field' => 'Image Upload',
            'custom-html-field' => 'Custom HTML',
        ),
        'Advanced Fields' => array(
            'action-hook-field' => 'Action Hook',
            'chained-select-field' => 'Chained Select',
            'checkable-grid-input-field' => 'Checkable Grid',
            'color-picker-field' => 'Color Picker',
            'custom-submit-button' => 'Custom Submit Button',
            'dynamic-field' => 'Dynamic Field',
            'fluentbooking-field' => 'FluentBooking',
            'gdpr-agreement-field' => 'GDPR Agreement',
            'hidden-input-field' => 'Hidden',
            'net-promoter-score' => 'Net Promoter Score (NPS)',
            'password-input-field' => 'Password',
            'quiz-score' => 'Quiz Score',
            'range-slider-field' => 'Range Slider',
            'ranking-field' => 'Ranking',
            'ratings-input-field' => 'Ratings',
            'repeat-input-field' => 'Repeat Field',
            'rich-text-input-field' => 'Rich Text',
            'save-progress-button' => 'Save Progress Button',
            'section-break' => 'Section Break',
            'shortcode-input-field' => 'Shortcode',
            'terms-conditions-field' => 'Terms & Conditions',
        ),
        'Container Fields' => array(
            'add-container-fields' => 'Container',
            'add-accordion-container-fields' => 'Accordion Container',
            'add-repeat-container-field' => 'Repeat Container',
            'resizeable-container' => 'Resizeable Container',
        ),
        'Post & Taxonomy Fields' => array(
            'add-post-title-field-in-post-forms' => 'Post Title',
            'add-post-content-field-in-post-forms' => 'Post Content',
            'add-post-excerpt-field-in-post-forms' => 'Post Excerpt',
            'add-featured-image-field-in-post-forms' => 'Featured Image',
            'add-post-update-field-in-post-forms' => 'Post Update',
            'add-categories-taxonomy-field-in-post-forms' => 'Categories',
            'add-tags-taxonomy-field-in-post-forms' => 'Tags',
        ),
    ),
    'Configuring Forms' => array(
        '_flat' => array(
            'configuring-forms-overview' => 'Overview',
        ),
        'Form Settings' => array(
            'error-message-customization' => 'Error Messages',
            'help-message-customization' => 'Help Messages',
            'restrict-blank-form-submission' => 'Restrict Blank Submission',
            'user-login-requirement' => 'Require User Login',
            'form-restrictions-feature' => 'Form Restrictions',
            'form-scheduling-feature' => 'Form Scheduling',
            'keyboard-navigation-shortcuts' => 'Keyboard Navigation & Shortcuts',
        ),
        'Conditional Logic & Dynamic Values' => array(
            'set-up-forms-with-conditional-logic' => 'Conditional Logic',
            'dynamic-default-value' => 'Dynamic Default Value',
            'set-default-form-value-from-url-parameters' => 'Default Value from URL',
            'dynamic-input-values-in-form-steps' => 'Dynamic Values in Steps',
            'unique-field-validation' => 'Unique Field Validation',
            'set-scroll-offset-of-form-steps' => 'Step Scroll Offset',
        ),
        'Calculations' => array(
            'numeric-calculation' => 'Numeric Calculation',
            'add-calc-values-on-the-repeat-field' => 'Calculations on Repeat Field',
        ),
    ),
    'Design & Styling' => array(
        'official-form-styler' => 'Official Form Styler',
        'form-layout-settings' => 'Layout Settings',
        'stylingcustom-css' => 'Custom CSS',
        'modalpopuplightbox' => 'Modal / Popup / Lightbox',
        'use-css-ready-classes' => 'CSS Ready Classes',
    ),
    'Notifications & Confirmations' => array(
        '_flat' => array(
            'notifications-confirmations-overview' => 'Overview',
        ),
        'Email Notifications' => array(
            'setup-adminuser-email-notifications' => 'Admin & User Notifications',
            'conditional-email-notification' => 'Conditional Notifications',
            'conditional-email-routing' => 'Conditional Email Routing',
            'weekly-email-summary' => 'Weekly Email Summary',
            'set-up-double-opt-in-emails' => 'Double Opt-in Emails',
            'not-sending-email-confirmations' => 'Emails Not Sending (Troubleshooting)',
        ),
        'Confirmations' => array(
            'setup-form-submission-confirmation-message' => 'Confirmation Message',
            'conditional-confirmation-message' => 'Conditional Confirmation',
            'shortcodes-in-confirmation-settings' => 'Shortcodes in Confirmations',
        ),
    ),
);